import type { Metadata } from 'next';
import { Manrope, Geist, Geist_Mono } from 'next/font/google';

import { Toaster } from '@/try-stuff/components/ui/sonner';
import { cn } from '@/try-stuff/lib/utils';

import './globals.css';
import { Header } from './header';
import { Footer } from './footer';
import { GoogleAnalytics } from './google-analytics';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: Check if we're in production then enable GA in future
  // const isProdEnv = process.env.NODE_ENV === 'production';
  const gaMeasurementId = 'G-6P1YY9WDWQ';

  return (
    <html lang="en">
      <body
        className={cn(
          `${manrope.variable} ${geistSans.variable} ${geistMono.variable} antialiased`,
          'grid min-h-screen grid-rows-[1fr,auto]',
        )}
      >
        {gaMeasurementId && (
          <GoogleAnalytics gaMeasurementId={gaMeasurementId} />
        )}
        <Header />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
