import type { News } from './types';

export const newsList: News[] = [
  {
    id: '1',
    url: 'https://news.gbimonthly.com/tw/article/show.php?num=74245',
    image: '/images/news/gbimonthly_logo.jpg',
    tag: 'global-bio-and-investment',
    title: '先勁智能AI落地彰濱秀傳 革新血癌與淋巴癌診斷',
    footer: '2025 Global Bio Investment Article',
  },
  {
    id: '2',
    url: 'https://www.thehubnews.net/archives/480531',
    image: '/images/news/the_hub_news.png',
    tag: 'the-hub-news',
    title: '彰濱秀傳與先勁智能合作　利用AI人工智慧革新血癌與淋巴癌診斷',
    footer: 'The Hub News 2025-02-06',
  },
  {
    id: '3',
    url: 'https://tw.news.yahoo.com/%E5%BD%B0%E6%BF%B1%E7%A7%80%E5%82%B3%E9%86%AB%E9%99%A2%E8%88%87%E5%85%88%E5%8B%81%E6%99%BA%E8%83%BD%E5%90%88%E4%BD%9C-%E7%94%A8ai%E9%9D%A9%E6%96%B0%E8%A1%80%E7%99%8C%E8%88%87%E6%B7%8B%E5%B7%B4%E7%99%8C%E8%A8%BA%E6%96%B7-124200974.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAANFQWaSbMcGJwsu12wypE-H2VesvxHm-ktPQryjel1dEIooedddIMujYQ8G9VWJMWpCCoEhIKjpN6SvhJ4BVHz3eekuVhJhx_Gs072ZBjY-DZ6zVbiF1n2ClmssW-3v6BmWfIpNd4O_6vIPYVtlTgoKf4RTjkMugHAuogghAIZ28',
    image: '/images/news/yahoo.jpg',
    tag: 'yahoo',
    title: '彰濱秀傳醫院與先勁智能合作 用AI革新血癌與淋巴癌診斷',
    footer: 'Yahoo News 2025-02-06',
  },
  {
    id: '4',
    url: 'https://www.storm.mg/article/5281954',
    image: '/images/news/ahead_x_thestormmedia_2.jpg',
    tag: 'the-storm-media',
    title: '血癌檢測百倍速！先勁智能創新AI輔助診斷技術，憑實力闖出名聲',
    footer: '2024 the storm media med ai award',
  },
  {
    id: '5',
    url: 'https://www.storm.mg/article/5244678',
    image: '/images/news/ahead_x_thestormmedia_1.jpg',
    tag: 'the-storm-media',
    title: '風傳媒「AI醫療領航大獎」 台北榮總、中國附醫、神瑞獲獎',
    footer: '2024 the storm media med ai award',
  },
  {
    id: '6',
    url: 'https://www.bnext.com.tw/article/79722/taiwan-ai-award-2024',
    image: '/images/news/bnext.jpg',
    tag: 'bnext',
    title: '2024台灣AI大賞｜台灣新護國神山，這10家台灣企業領跑AI市場',
    footer: '2024 BNEXT ai award',
  },
  {
    id: '7',
    url: 'https://www.bnext.com.tw/article/79724/ahead-medicine--taiwan-impact-ai-award-2024?fbclid=IwZXh0bgNhZW0CMTEAAR2FMKGfuNp44PijwiNORHP7YxyM2kUyLLuDPcIXXdxdpovs_gAh6UKws7M_aem_JVtBF8MwYFFhTdbMUCPEgQ',
    image: '/images/news/bnext_interview.png',
    tag: 'bnext',
    title:
      '2024台灣AI大賞｜7秒鐘找出異常細胞！先勁智能用AI加持判讀，成果登入聖經教科書',
    footer: '2024 BNEXT ai award',
  },
  {
    id: '8',
    url: 'https://news.gbimonthly.com/tw/magazine/article_show.php?num=68041',
    image: '/images/news/gbimonthly_logo.jpg',
    tag: 'global-bio-and-investment',
    title: '30分鐘變7秒!先勁智能AI血癌檢驗平台寫下經典教科書',
    footer: '2024 Global Bio Investment Article',
  },
  {
    id: '9',
    url: 'https://news.gbimonthly.com/tw/article/show.php?num=67379&page=1&category=&kw=%E6%95%B8%E4%BD%8D%E7%97%85%E7%90%86',
    image: '/images/news/gbimonthly_logo.jpg',
    tag: 'global-bio-and-investment',
    title: '數位病理學里程碑!美國IVD大廠Quest收購PathAI資產',
    footer: '2024 Global Bio Investment Article',
  },
  {
    id: '10',
    url: 'https://link.springer.com/protocol/10.1007/978-1-0716-3738-8_16',
    image: '/images/news/2024_flow_cytometry_protocols.png',
    title:
      'Using Artificial Intelligence to Interpret Clinical Flow Cytometry Datasets for Automated Disease Diagnosis and/or Monitoring',
    tag: 'protocols',
    footer: '2024 Flow Cytometry Protocols',
  },
];
